### ISSUE TITLE
Build new WWW site

### ISSUE THREAD

**Issue by joereddington** [eQualityTime/whitewaterwriters-site#1]
# Background
Over the last few days I've rebuilt [www.whitewaterwriters.com](https://www.whitewaterwriters.com/) from a site advertising the project to strangers into one that is focused on our writers. 

It's now a publisher's website because that's what the project is about: we help young writers publish their own novel and we should act like it.  

It was a bit of a mental struggle to make the change. Largely because I've never known how to market White Water Writers.  

Actually, I've never known if we _can_ market White Water Writers. It's a complex project that produces incredible results and nobody really believes in it until they see it working.  That's made worse by the half dosen companies that claim to do what we do, but don't.  The result is that most of our work is repeat work, and the vast marjority of our new work is by referral (a suprising amount of our new work is 'teacher from previous school moves to new school and calls us'). 

That means our website is mostly likely to be used by people we already work with (teachers, writers, parents of writers), or people who have already heard of us and want to check us out.  It's not a place for us to sell directly to faceless individuals.  

That's actually quite freeing - that means that the website doesn't have to worry about sales funnels or collecting emails, we can make it exactly how we like. 

I decided to keep it simple. We publish books, so we should have a book publisher's website. 

This has a bunch of advantages: 
* It _feels_ right. A lot of the value we give to our writers is that this is a real project and they really are publishing. So we should support that in every way we can. 
* It makes the books central rather than the process - and only I'm interested in the process. 
* It's _one_ simple angle: The project has to balance a research side, a process side, an advertising side, a charity development side and a parent-facing side.  That's a nightmare to write copy for on the same website and leaves us messy.  This website is going to be about what our writers have produced and everything else can go on [http://equalitytime.co.uk/](http://equalitytime.co.uk/)

From the technical side, this version will be easier to maintain and cheaper to host than the previous one (It's Github Pages rather than WordPress). I learned a lot putting it together and while I was doing it I migrated our email services away from a expensive host that I've grown to dislike (Dreamhost) to a free host that I trust (Google Suite). I suspect that all future sites will be on Github Pages.  You can read about all the technical challenges at [the project issue](https://github.com/eQualityTime/whitewaterwriters-site/issues/1).

# Todo
- [x] Get the [https://dayofcode.co.uk/](https://dayofcode.co.uk/) templates and check with Emma
- [x] Work throught the tutorial adding WWW information
- [ ] Find the Amazon data for books 
- [ ] Write the script to pull the data into the website
- [x] Add the Google Analytics information
- [x] Rewrite the text 
- [ ] Sort out the Images and books 
- [x] Fix the links in the authors section 
- [x] Add the news link to Facebook
- [x] Fix email 
    - [x] Import to Google Suite
- [x] Update Cover spreadsheet 
- [ ] Get all the images 
- [ ] Publish blog 
- [ ] link the costs post [http://equalitytime.co.uk/6417/2020/03/02/analysis-of-white-water-writers-camp-costs/]

**Comment by joereddington** [comment]
Okay, this needs rewriting because I've worked out what it should say, and it needs a few other bits: 

- [ ] Rewrite the text 
- [ ] Sort out the Images and books 
- [ ] Fix the links in the authors section 
- [ ] Add the news link to Facebook
- [ ] Add the google analytics information.

**Comment by joereddington** [comment]
Okay I've done a fair amount of work on [this steam]( https://youtu.be/e6O4KkqvaOc)  and the next action is to find the following cover images: 

BSDC2018 9339	Cover of BSDC2018 Flashback view 25
BSDC2019  11	Cover of BSDC2019 Hope view 33
Birches2018 9339	Cover of Birches2018 The Project view 85
BirchesHead  11	Cover of BirchesHead Poison Palace view 49
C2016 9339	Cover of C2016 Cloud Attack view 12
CCA2019  11	Cover of CCA2019 Pick `N' Mix: Do Animals Want to be Human?  view 47
CardinalNewman  11	Cover of CardinalNewman The Waiting view 93
Disc2018B
Haywood2019  11	Cover of Haywood2019 Patient Zero view 45
Liverpool2019  11	Cover of Liverpool2019 Mysticus view 42
NewVic2018 9339	Cover of NewVic2018 Grimm State of Mind view 31
Paget2018 9339	Cover of Paget2018 Matches view 39
Paget2018B 9339	Cover of Paget2018B When the Party's Over view 102
Paulet2018 9339	Cover of Paulet2018 Silence in the Woods view 57
Rudheath2019  11	Cover of Rudheath2019 The Secret view 87
SA2017year7 9339	Cover of SA2017year7 In the Shadows Where They Lie view 37
SUTH2017 9339	Cover of SUTH2017 The Mystery of the Purple Planet view 81
TCW2017 9339	Cover of TCW2017 Toxic Paradise: A London Story view 94
TGS2018TeamA 9339	Cover of TGS2018TeamA Punishment is Justice view 52
TGS2018TeamB 9339	Cover of TGS2018TeamB His Mind view 32
TGS2019B  11	Cover of TGS2019B The Chosen One view 66
TGS2019B 9339	Cover of TGS2019B The Chosen One view 65
WaPr2018 9339	Cover of WaPr2018 Duplicated view 19
bangor2018  11	Cover of bangor2018 Ash in a Thunderstorm view 2
discovery2018 9339	Cover of discovery2018 The Tentacles of Time view 89
firhill2018radicals 9339	Cover of firhill2018radicals Vengeance view 96
firhill2018raiders 9339	Cover of firhill2018raiders Project: Iris view 50
glyn2018TeamA 9339	Cover of glyn2018TeamA Russian Hybrids view 56
glyn2018TeamB 9339	Cover of glyn2018TeamB Chuck and the Goat Guy view 11
hw2017a 9339	Cover of hw2017a STRANDED!  view 60
hw2017b 9339	Cover of hw2017b The Disaster at Ryde Orphanage view 71
kingsdale2017
lde-c 9339	Cover of lde-c The D.O.T.  view 67
lde-ct 9339	Cover of lde-ct GAZA 7th view 28
lde-fm 9339	Cover of lde-fm Firewall view 24
lde-m 9339	Cover of lde-m The Difference Between Me and You view 70
lde-s 9339	Cover of lde-s ROYAL MURDER view 55
lde-sw 9339	Cover of lde-sw Identity Thief view 34
lde-t 9339	Cover of lde-t Sombra view 58
lde-w 9339	Cover of lde-w The Devil of the Mind view 69
oaks 9339	Cover of oaks The Future's Behind Us view 72
theoaks2018 9339	Cover of theoaks2018 The Other Side view 83
trentham 9339	Cover of trentham The Girl with Two Names view 74
trentham2018 9339	Cover of trentham2018 Pentagon Reversed view 46
watford2018 9339	Cover of watford2018 Feud of Fire view 22

**Comment by joereddington** [comment]
- [x] BSDC2018 9339 Cover of BSDC2018 Flashback view 25
 - [x] Birches2018 9339 Cover of Birches2018 The Project view 85
 - [x] MC2016 9339 Cover of C2016 Cloud Attack view 12
 - [ ] NewVic2018 9339 Cover of NewVic2018 Grimm State of Mind view 31
 - [ ] Paget2018 9339 Cover of Paget2018 Matches view 39
 - [ ] Paget2018B 9339 Cover of Paget2018B When the Party's Over view 102
 - [ ] Paulet2018 9339 Cover of Paulet2018 Silence in the Woods view 57
 - [ ] SA2017year7 9339 Cover of SA2017year7 In the Shadows Where They Lie view 37
 - [ ] SUTH2017 9339 Cover of SUTH2017 The Mystery of the Purple Planet view 81
 - [ ] TCW2017 9339 Cover of TCW2017 Toxic Paradise: A London Story view 94
 - [ ] TGS2018TeamA 9339 Cover of TGS2018TeamA Punishment is Justice view 52
 - [ ] TGS2018TeamB 9339 Cover of TGS2018TeamB His Mind view 32
 - [ ] TGS2019B 9339 Cover of TGS2019B The Chosen One view 65
 - [ ] WaPr2018 9339 Cover of WaPr2018 Duplicated view 19
 - [ ] discovery2018 9339 Cover of discovery2018 The Tentacles of Time view 89
 - [ ] firhill2018radicals 9339 Cover of firhill2018radicals Vengeance view 96
 - [ ] firhill2018raiders 9339 Cover of firhill2018raiders Project: Iris view 50
 - [ ] glyn2018TeamA 9339 Cover of glyn2018TeamA Russian Hybrids view 56
 - [ ] glyn2018TeamB 9339 Cover of glyn2018TeamB Chuck and the Goat Guy view 11
 - [ ] hw2017a 9339 Cover of hw2017a STRANDED! view 60
 - [ ] hw2017b 9339 Cover of hw2017b The Disaster at Ryde Orphanage view 71
 - [ ] kingsdale2017
 - [ ] lde-c 9339 Cover of lde-c The D.O.T. view 67
 - [ ] lde-ct 9339 Cover of lde-ct GAZA 7th view 28
 - [ ] lde-fm 9339 Cover of lde-fm Firewall view 24
 - [ ] lde-m 9339 Cover of lde-m The Difference Between Me and You view 70
 - [ ] lde-s 9339 Cover of lde-s ROYAL MURDER view 55
 - [ ] lde-sw 9339 Cover of lde-sw Identity Thief view 34
 - [ ] lde-t 9339 Cover of lde-t Sombra view 58
 - [ ] lde-w 9339 Cover of lde-w The Devil of the Mind view 69
 - [ ] oaks 9339 Cover of oaks The Future's Behind Us view 72
 - [ ] theoaks2018 9339 Cover of theoaks2018 The Other Side view 83
 - [ ] trentham 9339 Cover of trentham The Girl with Two Names view 74
 - [ ] trentham2018 9339 Cover of trentham2018 Pentagon Reversed view 46
 - [ ] watford2018 9339 Cover of watford2018 Feud of Fire view 22

**Comment by joereddington** [comment]
Today I've completed all the missing covers (at least for the list of allbooksever) and recorded a screencast showing how to do that.  As soon as the online version updates I'll move the site over.  

Oh, before that, I should record any missing informaiton on the site - I've put it here: https://docs.google.com/document/d/1yNGh8cWewNIObhDFb4zyTdpdt4q2dgKgyr6d6D-P5TQ/edit?usp=sharing

**Comment by joereddington** [comment]
## 04/03/20 10:39 to 13:03, Working on https://github.com/eQualityTime/whitewaterwriters-site/issues/1
* Added the missing covers 
* Fixed a bunch of bugs 
* Moved watchtower to an equalitytime.co.uk
* Used AWS to setup the redirection.

**Comment by joereddington** [comment]
Email.  Email is the problem that needs to be solved.

**Comment by joereddington** [comment]
I need to 

- [ ] Rewrite this issue 
- [ ] Get the missing books working 
- [ ] Check the google analytics

**Comment by joereddington** [comment]
## 11/09/20 07:00 to 10:24, Working on WWW website 
* Wrote up the article 
* Spent a lot of time getting the allbooksever.csv right. 
* Fixed the jekyll issues 

Things left to do: 

* Order the covers. 
* Push to server 
* 
* Write blog post.

**Comment by joereddington** [comment]
Fixing the GA for the site. 

## 13/09/20 14:51 to 15:03, Investigating why GA isn't working the new website. 
* I'm trying 'Tag Assistant', a chrome extension, as suggested here.  https://support.google.com/tagassistant/answer/2947093?hl=en
* Tag Assistant suggests that the GA number is UA-159578060-3, which I'm certain I changed. 
* I've removed _site from the github, added it to the .gitignore and pushed. 
* I found the old reference again and changed it [master acfb10a]
* Checked it works - it did, rapidly 

![Screenshot 2020-09-13 at 15 02 47](https://user-images.githubusercontent.com/4369547/93019965-5d91e080-f5d2-11ea-9c1e-584b7b93aafa.png)

**Comment by joereddington** [comment]
Two remaining things to fix. 

* Add a picture on the authors' page. 
* Fix the broken book page links.

**Comment by joereddington** [comment]
## 14/09/20 07:01 to 07:34,  Working on https://github.com/eQualityTime/whitewaterwriters-site/issues/1 +EQT
What did I learn and what should I have already known. 

* The site template I'm using making use of an external plugin to generate the book pages. Github doesn't support that so the files need to be served externally. 

* Rake is the Ruby Version of make, and there is a handy rakefile for publishing to gh-pages branches. That will be useful for future projects. 
* Ruby, or at least Jekyll, isn't working on my public streaming account. 
* There have been a bunch of commits today containing all the work and the notes. 
* You can serve a website from one account on a mac and see it from another, that's obvious but cool at the same time. 
* The dependabot alerts really do create pull requests: you have to click on the right bit. 
* I've updated the authors page with an image and more links. 

### What could I have done more elegantly
* I could have reversed the commit that removed the _site directory rather than adding it in again. I also could have squashed some commits together. 
* I could have fixed the Ruby/Jekyll issue first 
* I could have written a readme originally that said what was happening. 

#### Deploy notes for Joe
* You publish this site by writing: "rake blog:publish", you need to do that because Github pages doesn't like the plugin we use to generate the book pages

**Comment by joereddington** [comment]
Post is live here: http://equalitytime.co.uk/6439/2020/09/15/launching-a-new-white-water-writers-homepage/
